server:
  port: 8081  # Admin Server port

spring:
  application:
    name: sever-Admin  # Unique service name for Eureka
  boot:
    admin:
      ui:
        title: "Admin Dashboard"  # Optional
  security:
    user:
      name: admin
      password: admin  # Use this for secured access

eureka:
  client:
    service-url:
      # defaultZone: http://192.168.1.177:8761/eureka/  # Old Eureka Server URL (commented)
      defaultZone: http://localhost:8761/eureka/  # New Eureka Server URL
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true  # Registers with IP instead of hostname

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose all actuator endpoints
  endpoint:
    health:
      show-details: always
